"""add walk link signal paths

Revision ID: 8142db52dfa4
Revises: 
Create Date: 2026-08-14 16:37:09.201736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8142db52dfa4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('walk_links_file_path', sa.String(length=1024), nullable=False))
    op.add_column('areas', sa.Column('walk_signals_file_path', sa.String(length=1024), nullable=False))
    op.drop_index(op.f('ix_areas_name'), table_name='areas')
    op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=False)
    op.add_column('stop_data', sa.Column('area_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_stop_data_area_id'), 'stop_data', ['area_id'], unique=False)
    op.create_foreign_key(None, 'stop_data', 'areas', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stop_data', type_='foreignkey')
    op.drop_index(op.f('ix_stop_data_area_id'), table_name='stop_data')
    op.drop_column('stop_data', 'area_id')
    op.drop_index(op.f('ix_areas_name'), table_name='areas')
    op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=True)
    op.drop_column('areas', 'walk_signals_file_path')
    op.drop_column('areas', 'walk_links_file_path')
    # ### end Alembic commands ###
